apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: backend-ms-trigger-binding-dev
spec:
  params:
  - name: git-repo-url
    value: https://github.com/$(body.repository.full_name).git
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.ref)
  - name: NAMESPACE
    value: tekton-demo-dev   # ✅ hardcoded value here