apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: backend-ms-trigger-dev
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: backend-ms-trigger-binding-dev
  template:
    ref: backend-ms-trigger-template-dev
