apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: backend-ms-trigger-staging
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["create"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "body.ref_type == 'tag' && body.ref.startsWith('release')"
  bindings:
    - ref: backend-ms-trigger-binding-staging
  template:
    ref: backend-ms-trigger-template-staging
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
