apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: backend-ms
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: backend-ms-trigger     # existing trigger for dev
    - triggerRef: backend-ms-trigger-qa  # new trigger for qa (tags only)