apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: el-backend-ms-cross-namespace-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-demo-dev  # ← this is where your EventListener SA is located
roleRef:
  kind: ClusterRole
  name: tekton-triggers-admin   # ← gives permission to create PipelineRuns in any namespace
  apiGroup: rbac.authorization.k8s.io
