apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-ms
  name: backend-ms
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: backend-ms