apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automatiko-tekton-crd-access
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["customruns"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: automatiko-tekton-crd-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: automatiko
roleRef:
  kind: ClusterRole
  name: automatiko-tekton-crd-access
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automatiko-approvaltask-role
rules:
  - apiGroups: ["tekton.automatiko.io"]
    resources: ["approvaltasks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: automatiko-approvaltask-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: automatiko
roleRef:
  kind: ClusterRole
  name: automatiko-approvaltask-role
  apiGroup: rbac.authorization.k8s.io
